#!/bin/bash

script_location="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

check_installed=$(which meteor-jscs-git-hooks)
if [[ check_installed ]]; then
	meteor-jscs-git-hooks 'pre-commit'
else
	echo "NPM-package not installed. Please re-install via `npm install meteor-jscs-git-hooks`"
fi